import React, { useState } from 'react';
import { FileText, Download, Calendar, TrendingUp, Shield, AlertTriangle, CheckCircle, XCircle } from 'lucide-react';

interface Report {
  id: string;
  title: string;
  date: string;
  type: 'attack' | 'defense' | 'summary';
  status: 'success' | 'warning' | 'critical';
  metrics: {
    totalAttacks: number;
    blocked: number;
    failed: number;
    avgResponseTime: string;
  };
}

export const ReportingView: React.FC = () => {
  const [selectedPeriod, setSelectedPeriod] = useState('today');
  
  const reports: Report[] = [
    {
      id: '1',
      title: 'Daily Security Report',
      date: new Date().toLocaleDateString(),
      type: 'summary',
      status: 'success',
      metrics: {
        totalAttacks: 24,
        blocked: 22,
        failed: 2,
        avgResponseTime: '1.8s'
      }
    },
    {
      id: '2',
      title: 'Red Team Assessment',
      date: new Date().toLocaleDateString(),
      type: 'attack',
      status: 'warning',
      metrics: {
        totalAttacks: 15,
        blocked: 12,
        failed: 3,
        avgResponseTime: '2.1s'
      }
    },
    {
      id: '3',
      title: 'Blue Team Performance',
      date: new Date().toLocaleDateString(),
      type: 'defense',
      status: 'success',
      metrics: {
        totalAttacks: 9,
        blocked: 9,
        failed: 0,
        avgResponseTime: '1.5s'
      }
    }
  ];

  const stats = {
    totalIncidents: 24,
    resolved: 22,
    pending: 2,
    criticalThreats: 0,
    successRate: 92,
    avgResponseTime: '1.8s',
    topAttackType: 'SQL Injection',
    topDefender: 'Sentinel-AI'
  };

  const exportReport = (reportId: string) => {
    const report = reports.find(r => r.id === reportId);
    if (!report) return;

    const content = `
CyberSentinel Security Report
=============================

Report: ${report.title}
Date: ${report.date}
Type: ${report.type.toUpperCase()}
Status: ${report.status.toUpperCase()}

Metrics:
--------
Total Attacks: ${report.metrics.totalAttacks}
Blocked: ${report.metrics.blocked}
Failed: ${report.metrics.failed}
Success Rate: ${((report.metrics.blocked / report.metrics.totalAttacks) * 100).toFixed(1)}%
Avg Response Time: ${report.metrics.avgResponseTime}

Generated by CyberSentinel AI Platform
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `cybersentinel-report-${report.id}-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between border-b border-slate-800 pb-4">
        <div className="flex items-center gap-3">
          <div className="p-2 bg-purple-500/10 rounded-lg">
            <FileText className="text-purple-400" size={28} />
          </div>
          <div>
            <h2 className="text-2xl font-bold text-white">Security Reports</h2>
            <p className="text-slate-400 text-sm">Comprehensive analysis and metrics</p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <select
            value={selectedPeriod}
            onChange={(e) => setSelectedPeriod(e.target.value)}
            className="px-4 py-2 bg-slate-900 border border-slate-700 rounded-lg text-white text-sm focus:outline-none focus:border-purple-500"
          >
            <option value="today">Today</option>
            <option value="week">This Week</option>
            <option value="month">This Month</option>
            <option value="all">All Time</option>
          </select>
        </div>
      </div>

      {/* Stats Grid */}
      <div className="grid grid-cols-4 gap-4">
        <div className="bg-slate-900/50 border border-slate-800 rounded-xl p-4">
          <div className="flex items-center justify-between mb-2">
            <span className="text-slate-400 text-sm">Total Incidents</span>
            <AlertTriangle className="text-yellow-400" size={20} />
          </div>
          <div className="text-3xl font-bold text-white">{stats.totalIncidents}</div>
          <div className="text-xs text-slate-500 mt-1">+12% from yesterday</div>
        </div>

        <div className="bg-slate-900/50 border border-green-900/50 rounded-xl p-4">
          <div className="flex items-center justify-between mb-2">
            <span className="text-slate-400 text-sm">Resolved</span>
            <CheckCircle className="text-green-400" size={20} />
          </div>
          <div className="text-3xl font-bold text-green-400">{stats.resolved}</div>
          <div className="text-xs text-slate-500 mt-1">{stats.successRate}% success rate</div>
        </div>

        <div className="bg-slate-900/50 border border-red-900/50 rounded-xl p-4">
          <div className="flex items-center justify-between mb-2">
            <span className="text-slate-400 text-sm">Failed</span>
            <XCircle className="text-red-400" size={20} />
          </div>
          <div className="text-3xl font-bold text-red-400">{stats.pending}</div>
          <div className="text-xs text-slate-500 mt-1">Requires attention</div>
        </div>

        <div className="bg-slate-900/50 border border-blue-900/50 rounded-xl p-4">
          <div className="flex items-center justify-between mb-2">
            <span className="text-slate-400 text-sm">Avg Response</span>
            <TrendingUp className="text-blue-400" size={20} />
          </div>
          <div className="text-3xl font-bold text-blue-400">{stats.avgResponseTime}</div>
          <div className="text-xs text-slate-500 mt-1">-0.3s improvement</div>
        </div>
      </div>

      {/* Key Insights */}
      <div className="grid grid-cols-2 gap-4">
        <div className="bg-slate-900/50 border border-slate-800 rounded-xl p-6">
          <h3 className="text-lg font-bold text-white mb-4 flex items-center gap-2">
            <Shield size={20} className="text-blue-400" />
            Top Performing Agent
          </h3>
          <div className="space-y-3">
            <div className="flex items-center justify-between p-3 bg-slate-950 rounded-lg border border-blue-900/50">
              <div>
                <div className="font-bold text-white">{stats.topDefender}</div>
                <div className="text-xs text-slate-400">Threat Detection System</div>
              </div>
              <div className="text-right">
                <div className="text-2xl font-bold text-blue-400">98%</div>
                <div className="text-xs text-slate-500">Success Rate</div>
              </div>
            </div>
            <div className="text-sm text-slate-400">
              Blocked 22 out of 22 detected threats with average response time of 1.5 seconds.
            </div>
          </div>
        </div>

        <div className="bg-slate-900/50 border border-slate-800 rounded-xl p-6">
          <h3 className="text-lg font-bold text-white mb-4 flex items-center gap-2">
            <AlertTriangle size={20} className="text-red-400" />
            Most Common Attack
          </h3>
          <div className="space-y-3">
            <div className="flex items-center justify-between p-3 bg-slate-950 rounded-lg border border-red-900/50">
              <div>
                <div className="font-bold text-white">{stats.topAttackType}</div>
                <div className="text-xs text-slate-400">Database Attack Vector</div>
              </div>
              <div className="text-right">
                <div className="text-2xl font-bold text-red-400">8</div>
                <div className="text-xs text-slate-500">Attempts</div>
              </div>
            </div>
            <div className="text-sm text-slate-400">
              All attempts were successfully blocked by WAF and input validation layers.
            </div>
          </div>
        </div>
      </div>

      {/* Reports List */}
      <div className="bg-slate-900/50 border border-slate-800 rounded-xl p-6">
        <h3 className="text-lg font-bold text-white mb-4 flex items-center gap-2">
          <Calendar size={20} />
          Generated Reports
        </h3>
        <div className="space-y-3">
          {reports.map(report => (
            <div
              key={report.id}
              className="flex items-center justify-between p-4 bg-slate-950 rounded-lg border border-slate-800 hover:border-slate-700 transition-colors"
            >
              <div className="flex items-center gap-4">
                <div className={`p-3 rounded-lg ${
                  report.type === 'attack' ? 'bg-red-900/20 text-red-400' :
                  report.type === 'defense' ? 'bg-blue-900/20 text-blue-400' :
                  'bg-purple-900/20 text-purple-400'
                }`}>
                  <FileText size={20} />
                </div>
                <div>
                  <div className="font-bold text-white">{report.title}</div>
                  <div className="text-xs text-slate-400">{report.date}</div>
                </div>
              </div>

              <div className="flex items-center gap-6">
                <div className="text-right">
                  <div className="text-sm text-slate-400">Success Rate</div>
                  <div className={`text-lg font-bold ${
                    report.status === 'success' ? 'text-green-400' :
                    report.status === 'warning' ? 'text-yellow-400' :
                    'text-red-400'
                  }`}>
                    {((report.metrics.blocked / report.metrics.totalAttacks) * 100).toFixed(0)}%
                  </div>
                </div>

                <div className="text-right">
                  <div className="text-sm text-slate-400">Attacks</div>
                  <div className="text-lg font-bold text-white">{report.metrics.totalAttacks}</div>
                </div>

                <button
                  onClick={() => exportReport(report.id)}
                  className="flex items-center gap-2 px-4 py-2 bg-purple-600 hover:bg-purple-500 text-white rounded-lg text-sm font-bold transition-all"
                >
                  <Download size={16} />
                  Export
                </button>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Timeline */}
      <div className="bg-slate-900/50 border border-slate-800 rounded-xl p-6">
        <h3 className="text-lg font-bold text-white mb-4">Activity Timeline</h3>
        <div className="space-y-4">
          {[
            { time: '14:32', event: 'SQL Injection blocked by Sentinel-AI', type: 'success' },
            { time: '14:28', event: 'Brute force attempt detected', type: 'warning' },
            { time: '14:15', event: 'XSS attack mitigated by Guardian-Firewall', type: 'success' },
            { time: '14:02', event: 'Phishing campaign analyzed', type: 'info' },
            { time: '13:45', event: 'System scan completed', type: 'info' },
          ].map((item, idx) => (
            <div key={idx} className="flex items-start gap-4">
              <div className="text-xs text-slate-500 w-16">{item.time}</div>
              <div className={`w-2 h-2 rounded-full mt-1.5 ${
                item.type === 'success' ? 'bg-green-400' :
                item.type === 'warning' ? 'bg-yellow-400' :
                'bg-blue-400'
              }`} />
              <div className="flex-1 text-sm text-slate-300">{item.event}</div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};
