import { useState, useEffect } from "react";
import { FileText, Download, TrendingUp, Shield, AlertTriangle, CheckCircle, XCircle } from "lucide-react";
import { api } from "../api/client";

export default function ReportingView() {
  const [report, setReport]   = useState(null);
  const [loading, setLoading] = useState(true);
  const [period, setPeriod]   = useState("today");

  useEffect(() => {
    api.getReport()
      .then(setReport)
      .catch(() => setReport(null))
      .finally(() => setLoading(false));
  }, [period]);

  const exportTxt = () => {
    if (!report) return;
    const content = `CyberSentinel Security Report\n${"=".repeat(40)}\nDate: ${new Date().toLocaleString()}\n\nTotal Attacks: ${report.total_attacks}\nBlocked: ${report.blocked}\nFailed: ${report.failed}\nSuccess Rate: ${report.success_rate}%\n\nTop Defender: ${report.top_defender?.name || "N/A"} (${report.top_defender?.blocks || 0} blocks)\n\nAttacks by Type:\n${Object.entries(report.attacks_by_type || {}).map(([k,v]) => `  ${k}: ${v}`).join("\n")}\n\nTimeline:\n${(report.timeline || []).map(t => `  [${t.time}] ${t.event}`).join("\n")}\n\nGenerated by CyberSentinel — Gemini 3 Hackathon`;
    const blob = new Blob([content], { type: "text/plain" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = `cybersentinel-report-${Date.now()}.txt`;
    a.click();
  };

  if (loading) return (
    <div className="flex items-center justify-center h-64">
      <div className="text-slate-400 font-mono animate-pulse">Loading report data...</div>
    </div>
  );

  const r = report || { total_attacks: 0, blocked: 0, failed: 0, success_rate: 0, attacks_by_type: {}, timeline: [], top_defender: null };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between border-b border-slate-800 pb-4">
        <div className="flex items-center gap-3">
          <div className="p-2 bg-purple-500/10 rounded-lg">
            <FileText className="text-purple-400" size={24} />
          </div>
          <div>
            <h2 className="text-2xl font-bold text-white">Security Reports</h2>
            <p className="text-slate-400 text-sm">Analyst-only analytics dashboard</p>
          </div>
        </div>
        <div className="flex items-center gap-3">
          <select value={period} onChange={e => setPeriod(e.target.value)}
            className="px-3 py-2 bg-slate-900 border border-slate-700 rounded-lg text-white text-sm focus:outline-none focus:border-purple-500">
            <option value="today">Today</option>
            <option value="week">This Week</option>
            <option value="month">This Month</option>
          </select>
          <button onClick={exportTxt}
            className="flex items-center gap-2 px-4 py-2 bg-purple-600 hover:bg-purple-500 text-white rounded-lg text-sm font-bold transition-all">
            <Download size={16} />Export
          </button>
        </div>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-4 gap-4">
        {[
          { label: "Total Attacks",  value: r.total_attacks,  icon: AlertTriangle, color: "yellow" },
          { label: "Blocked",        value: r.blocked,         icon: CheckCircle,   color: "green"  },
          { label: "Failed",         value: r.failed,          icon: XCircle,       color: "red"    },
          { label: "Success Rate",   value: `${r.success_rate}%`, icon: TrendingUp, color: "blue"   },
        ].map(({ label, value, icon: Icon, color }) => (
          <div key={label} className={`bg-slate-900/50 border rounded-xl p-5 border-${color}-900/50`}>
            <div className="flex items-center justify-between mb-2">
              <span className="text-slate-400 text-sm">{label}</span>
              <Icon size={20} className={`text-${color}-400`} />
            </div>
            <div className={`text-3xl font-bold text-${color}-400`}>{value}</div>
          </div>
        ))}
      </div>

      <div className="grid grid-cols-2 gap-6">
        {/* Attacks by type */}
        <div className="bg-slate-900/50 border border-slate-800 rounded-xl p-6">
          <h3 className="font-bold text-white mb-4 flex items-center gap-2">
            <AlertTriangle size={16} className="text-red-400" />Attacks by Type
          </h3>
          {Object.keys(r.attacks_by_type).length === 0 ? (
            <p className="text-slate-600 text-sm italic">No attacks recorded yet</p>
          ) : (
            <div className="space-y-3">
              {Object.entries(r.attacks_by_type).sort((a,b) => b[1]-a[1]).map(([type, count]) => {
                const max = Math.max(...Object.values(r.attacks_by_type));
                return (
                  <div key={type}>
                    <div className="flex justify-between text-sm mb-1">
                      <span className="text-slate-300">{type}</span>
                      <span className="text-slate-400 font-mono">{count}</span>
                    </div>
                    <div className="h-1.5 bg-slate-800 rounded-full">
                      <div className="h-full bg-red-500 rounded-full transition-all" style={{ width: `${(count/max)*100}%` }} />
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>

        {/* Top defender + timeline */}
        <div className="space-y-4">
          {r.top_defender?.name && (
            <div className="bg-slate-900/50 border border-green-900/30 rounded-xl p-5">
              <h3 className="font-bold text-white mb-3 flex items-center gap-2">
                <Shield size={16} className="text-blue-400" />Top Defender
              </h3>
              <div className="flex items-center justify-between p-3 bg-slate-950 rounded-lg border border-blue-900/30">
                <div>
                  <div className="font-bold text-white">{r.top_defender.name}</div>
                  <div className="text-xs text-slate-400">Blue Team Agent</div>
                </div>
                <div className="text-right">
                  <div className="text-2xl font-bold text-blue-400">{r.top_defender.blocks}</div>
                  <div className="text-xs text-slate-500">blocks</div>
                </div>
              </div>
            </div>
          )}

          <div className="bg-slate-900/50 border border-slate-800 rounded-xl p-5 flex-1">
            <h3 className="font-bold text-white mb-3">Activity Timeline</h3>
            <div className="space-y-2 max-h-48 overflow-y-auto">
              {r.timeline.length === 0 && <p className="text-slate-600 text-sm italic">No activity yet</p>}
              {r.timeline.map((t, i) => (
                <div key={i} className="flex items-start gap-3 text-xs">
                  <span className="text-slate-500 font-mono shrink-0">{t.time}</span>
                  <div className={`w-1.5 h-1.5 rounded-full mt-1 shrink-0 ${t.type === "attack" ? "bg-red-500" : "bg-blue-500"}`} />
                  <span className="text-slate-300">{t.event}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
